apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-minio
spec:
  selector:
    matchLabels:
      app: triton-minio
  template:
    metadata:
      labels:
        app: triton-minio
    spec:
      volumes:
      - name: triton-pvc
        persistentVolumeClaim:
          claimName: triton-pvc
      containers:
      - name: triton-minio
        image: quay.io/minio/minio:latest
        command:
        - /bin/bash
        - -c
        args:
        - minio server /data --console-address :9090
        volumeMounts:
        - name: triton-pvc
          mountPath: '/data'
        env:
        - name: MINIO_ACCESS_KEY
          value: "minioadmin"
        - name: MINIO_SECRET_KEY
          value: "minioadmin"
        - name: MINIO_BROWSER_REDIRECT_URL
          value: "http://triton-minio-console.mlops-sandbox.com"
        - name: MINIO_SERVER_URL
          value: "http://triton-minio.mlops-sandbox.com"
        ports:
        - containerPort: 9000
        - containerPort: 9090
        
---
apiVersion: v1
kind: Service
metadata:
  name: triton-minio-service
spec:
  type: NodePort
  ports:
  - port: 9000
    targetPort: 9000
    protocol: TCP
    name: api
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: console
  selector:
    app: triton-minio
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: triton-minio-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "false"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: ""
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
spec:
  rules:
  - host: triton-minio.mlops-sandbox.com
    http:
      paths:
        - backend:
            service:
              name: triton-minio-service
              port:
                number: 9000
          path: /
          pathType: Prefix
  - host: triton-minio-console.mlops-sandbox.com
    http:
      paths:
        - backend:
            service:
              name: triton-minio-service
              port:
                number: 9090
          path: /
          pathType: Prefix

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi