apiVersion: apps/v1
kind: Deployment
metadata:
  name: triton-server
spec:
  selector:
    matchLabels:
      app: triton-server
  template:
    metadata:
      labels:
        app: triton-server
    spec:
      volumes:
      - name: triton-server-pvc
        persistentVolumeClaim:
          claimName: triton-server-pvc
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: triton-minio
        image: nvcr.io/nvidia/tritonserver:22.07-py3
        command:
        - /bin/bash
        - -c
        args:
        - tritonserver --model-store=s3://triton-minio-service.triton.svc.cluster.local:9000/models/smartpay-merchant-fraud-prepaid-v5 --load-model=* --model-control-mode="explicit" --exit-on-error=false
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        env:
        - name: AWS_ACCESS_KEY_ID
          value: "minioadmin"
        - name: AWS_SECRET_ACCESS_KEY
          value: "minioadmin"
        ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
        
---
apiVersion: v1
kind: Service
metadata:
  name: triton-server-service
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: grpc
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: metrics
  selector:
    app: triton-server
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: triton-minio-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "false"
    kubernetes.io/ingress.allow-http: "false"
    kubernetes.io/ingress.global-static-ip-name: ""
    nginx.ingress.kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
spec:
  rules:
  - host: triton-server.mlops-sandbox.com
    http:
      paths:
        - backend:
            service:
              name: triton-server-service
              port:
                number: 8000
          path: /
          pathType: Prefix
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triton-server-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi